<?php

declare(strict_types=1);

namespace SearchSpring\Feed\Test\Integration\Api;

use PHPUnit\Framework\TestCase;

class ExecuteTaskInterfaceTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExecute() : void
    {

    }

    public function testExecuteInvalidTask() : void
    {

    }
}
