<?php
/**
 * Copyright (C) 2023 Searchspring <https://searchspring.com>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace SearchSpring\Feed\Test\Integration\Api;

use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\ObjectManagerInterface;
use PHPUnit\Framework\TestCase;
use Magento\TestFramework\Helper\Bootstrap;
use SearchSpring\Feed\Api\GenerateFeedInterface;
use SearchSpring\Feed\Exception\GenericException;
use SearchSpring\Feed\Model\Feed\SpecificationBuilderInterface;

/**
 *
 * @magentoDbIsolation enabled
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class GenerateFeedInterfaceTest extends TestCase
{
    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;
    /**
     * @var GenerateFeedInterface
     */
    private $generateFeed;
    /**
     * @var SpecificationBuilderInterface
     */
    private $feedSpecificationBuilder;

    /**
     *
     */
    protected function setUp(): void
    {
        $this->objectManager = Bootstrap::getObjectManager();
        $this->generateFeed = $this->objectManager->get(GenerateFeedInterface::class);
        $this->feedSpecificationBuilder = $this->objectManager->get(SpecificationBuilderInterface::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * test that all components works together and we do not have exceptions in regular process
     * components business logic tested in specific component tests
     *
     * @magentoAppIsolation enabled
     * @magentoDataFixture SearchSpring_Feed::Test/_files/configure_aws_client_mock.php
     * @magentoDataFixture SearchSpring_Feed::Test/_files/simple_products.php
     *
     * @return void
     * @throws GenericException
     */
    public function testExecute() : void
    {
        $specification = $this->feedSpecificationBuilder->build($this->getPayload());
        $this->generateFeed->execute($specification);
        // check that we achieve this place and dont have any exceptions
        $this->assertEquals(1,1);
    }

    /**
     * @return array
     */
    private function getPayload() : array
    {
        return [
            'preSignedUrl' => 'https://testurl.com'
        ];
    }
}
