<?php

declare(strict_types=1);

namespace SearchSpring\Feed\Test\Integration\Api;

use PHPUnit\Framework\TestCase;

class TestRepositoryInterfaceTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGet() : void
    {

    }

    public function testGetWithInvalidId() : void
    {

    }

    public function testGetList() : void
    {

    }

    public function testGetListEmpty() : void
    {

    }

    public function testGetListWithStatusAndTypeFilter() : void
    {

    }

    public function testSave() : void
    {

    }

    public function testDelete() : void
    {

    }

    public function testDeleteNewModelInstance() : void
    {

    }

    public function testDeleteById() : void
    {

    }

    public function testDeleteByIdWithNotExistedId() : void
    {

    }
}
